### ISSUE TITLE
About the taxi experiments

### ISSUE THREAD

**Issue by Roxyi** [alasdairtran/radflow#2]
Hi, thank you for sharing the code implementation. I started with the taxi experiment since my dataset is similar to the taxi datasets. However, I didn't find the key2pos_path in the config.yaml. Does it mean that in the taxi experiments, you are not using the flow aggregation component and the model is purely based on the recurrent component?

**Comment by alasdairtran** [comment]
The flow aggregation component is used in the taxi datasets.

If you check [this for loop](https://github.com/alasdairtran/radflow/blob/df473bf09b6aa7ae890305aa3b469a9cba180f2e/radflow/models/radflow.py#L498) in the Radflow code, you'll see that if `key2pos_path` is not provided, then we just set the mask to zeros, which means that we're attending to a neighbour for every time step. 

The `key2pos_path` is useful when we have a dynamic graph, in which an edge can appear or disappear over time. Our Vevo and Wiki datasets have this property. The taxi datasets, on the other hand, is a static network (i.e. if two roads are connected, they remain connected for all steps).

**Comment by Roxyi** [comment]
@alasdairtran Got you and thank you. Could you please upload the taxi h5 data to https://cloudstor.aarnet.edu.au/plus/s/wQbOswE7qi50mci ? I found one in a T-GCN repository https://github.com/zouchangjie/T-GCN--------/tree/master/data, but their h5 doesn't have edges information. I guess I could construct edges based on the adjacency file, but I just wanna make sure I use the same data as you did in your experiment.

**Comment by alasdairtran** [comment]
Sure I've just uploaded the taxi datasets to `data/taxi` in our Cloudstor drive.
